### ISSUE TITLE
catalina.sh is missing from project

### ISSUE THREAD

**Issue by kempstonjoystick** [secure-device-onboard/all-in-one-demo#11]
The instructions for running the project state the following:

> Open a terminal and execute following command.
> 
> ```
> sh tomcat/bin/catalina.sh run
> ```

Additionally, the Dockerfile for the project specifies the same file as the entrypoint. However, in both the master and 18.1-rel branches, there is no tomcat/bin directory.

**Comment by trbehera** [comment]
In container/overlay/tomcat folder contains the tomcat distribution files that are modified for all-in-one demo. While building the demo, the tomcat distribution zip file is downloaded and these files are copied.

Build the package using instructions provided in README or use the v1.8.0 release tarball (https://github.com/secure-device-onboard-ci/release/releases/download/v1.8.0/all-in-one-demo-v1.8.0.tar.gz) for demo.

**Comment by kempstonjoystick** [comment]
Hi there, my mistake was executing the docker-compose command from the container/overlay directory rather than target/deploy.

Thanks for the reply.
